version: '3'
services:
  
  api:
    build: ../../src/Palavras.Web.API/.
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    ports:
    - 5001:80
      
  schedule:
    build: ../../src/Palavras.Background.ETL/.
    restart: always
    environment:
      TZ: "America/Sao_Paulo"

  spa:
    build: ../../src/Palavras.Web.SPA/.
    ports:
      - '80:80'
