version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=password
      - xpack.security.enabled=true
    ports:
      - 9200:9200
    networks: ['stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=password
    ports: ['5601:5601']
    networks: ['stack']
    links: ['elasticsearch']
    depends_on: ['elasticsearch']
    
  api:
    build: ../../src/Palavras.Web.API/.
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    ports:
    - 5001:5001

  schedule:
    build: ../../src/Palavras.Background.ETL/.
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
  spa:
    build: ../../src/Palavras.Web.SPA/.
    ports:
      - '80:80'
networks:
  stack: {}