FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy everything else and build
COPY ./ ./
RUN dotnet publish ./Scraping.Web.MVC/Scraping.Web.MVC.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .

EXPOSE 5001
ENTRYPOINT ["dotnet", "Scraping.Web.MVC.dll"]