module.exports = {
    sinalList : [
        "/❮/g",
        "/❯/g",
        "/:/g",
        "/;/g",
        "/,/g",
        "/./g",
        "/-/g",
        "/.../g",
        "/'/g",
    ],
    blackList :
     [
        " a ",
        " as ",
        " o ",
        " os ",
        " oa ",
        " aos ",
        " e ",
        " da ",
        " do ",
        " de ",
        " na ",
        " no ",
        " ano ",
        " se ",
        " isso ",
        " disso ",
        " disto ",
        " é ",
        " por ",
        " que ",
        " em ",
        " diz ",
        " mas ",
        " mais ",
        " têm ",
        " tiveram ",
        " com ",
        " como ",
        " pelo ",
        " ao ",
        " tem ",
        " ficam ",
        " fica ",
        " ficou ",
        " nos ",
        " não ",
        " para ",
        " um ",
        " uma ",
        " sobre ",
        "\\n",
      
    ]
}